export const siteConfig = Object.freeze({
  businessName: 'FlameFix Gas Services',
  shortName: 'FlameFix',
  tagline: 'Chimney & gas appliance repair in Bhopal.',
  phoneDisplay: '+91 92013 39300',
  phoneHref: '+919201339300',
  whatsappNumber: '919201339300',
  email: 'service@yourbusiness.com',
  serviceArea: 'MP Nagar, Bhopal & Nearby Areas',
  city: 'Bhopal',
  state: 'Madhya Pradesh',
  locality: 'MP Nagar',
  hours: '8:00 AM – 10:00 PM',
  responseText: 'Same-day appointments available',
  visitFeeText: 'Inspection charges are confirmed before the visit.',
  copyrightYear: new Date().getFullYear(),
  siteUrl: 'https://chimneygasrepairbhopal.com',
});
